export default {
  DELETE_PEOPLE : 'DELETE_PEOPLE',
  ADD_PEOPLE    : 'ADD_PEOPLE',
  GET_PEOPLE    : 'GET_PEOPLE',
  UPDATE_PEOPLE : 'UPDATE_PEOPLE',
  VERIFY_EMAIL  : 'VERIFY_EMAIL',
  CLEAR_ALL   : 'CLEAR_ALL'
};
